### ISSUE TITLE
type piracy 

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/ParallelMergeCSR.jl#27]
~We should get rid of this type of piracy by switching to a different name, otherwise, this will invalidate the original `mul!` method, we should support this by an `if-else` inside Bloqade and other packages calling the function.~

https://github.com/QuEraComputing/ParallelMergeCSR.jl/blob/eabcc552cdc2d67258471f2ad099c3a2ba956952/src/ParallelMergeCSR.jl#L194

~It's a bit annoying, but things have to be done in this way until we have method overlay support from Julia compiler.~

nvm, I just realize it's not overloaded.

**Comment by Roger-luo** [comment]
I think then we shouldn't export it, or should use a different name because this will cause the following if using it naively

```julia
julia> mul!(y, A, b, 1.0, 0.0)
WARNING: both LinearAlgebra and ParallelMergeCSR export "mul!"; uses of it in module Main must be qualified
ERROR: UndefVarError: mul! not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

**Comment by weinbe58** [comment]
Good point, we don't need to export the function

**Comment by johnzl-777** [comment]
> Good point, we don't need to export the function

#29 goes down this route 🤠
